FROM registry.access.redhat.com/ubi9/python-39

LABEL maintainer="you@example.com"
ENV PYTHONUNBUFFERED=1 \
    PORT=8080 \
    ANSIBLE_LINT_NO_CACHE=1

# Use OpenShift-safe working directory
WORKDIR /opt/app-root/src

# Copy dependencies and install
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/main.py .

EXPOSE 8080
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
